/*
 * Copyright 2017, TeamDev Ltd. All rights reserved.
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.spine3.test;

import com.google.protobuf.Message;
import org.spine3.client.CommandFactory;

/**
 * The abstract base for testing a command handling method.
 *
 * <p>Examples of such classes are: {@code Aggregate}, {@code AggregatePart}, and {@code ProcessManager}.
 *
 * <p>A test suite derived from this class should test:
 * <ol>
 *     <li>events generated by the handling method
 *     <li>state modified as the result of handling the command
 *     <li>failures (if declared) that are generated
 * </ol>
 *
 * @param <C> the type of the command message that we test in the suite
 * @author Alexander Yevsyukov
 */
abstract class CommandHandlingTest<C extends Message> extends CommandTest<C> {

    /**
     * {@inheritDoc}
     */
    protected CommandHandlingTest(CommandFactory commandFactory) {
        super(commandFactory);
    }

    /**
     * {@inheritDoc}
     */
    protected CommandHandlingTest() {
        super();
    }

    /**
     * Implement this method to create and store the reference to the object
     * (like {@code Aggregate} or {@code AggregatePart}) which is going to be used
     * in a test method that would follow.
     *
     * <p>This method must be called in derived test suites in methods
     * annotated with {@code @Before} (JUnit 4) or {@code @BeforeEach} (JUnit 5).
     */
    protected abstract void setUp();
}
