/*
 * Copyright 2017, TeamDev Ltd. All rights reserved.
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.spine3.server.storage;

import com.google.protobuf.Message;
import org.spine3.server.aggregate.Aggregate;
import org.spine3.server.aggregate.AggregateStorage;
import org.spine3.server.commandstore.CommandStore;
import org.spine3.server.entity.storage.ColumnTypeRegistry;
import org.spine3.server.projection.ProjectionStorage;
import org.spine3.server.stand.StandStorage;

/**
 * A factory for creating storages used by repositories,
 * {@link CommandStore CommandStore},
 * {@link org.spine3.server.event.EventStore EventStore},
 * and {@link org.spine3.server.stand.Stand Stand}.
 *
 * @author Alexander Yevsyukov
 */
public interface StorageFactory extends AutoCloseable {

    /**
     * Verifies if the storage factory is configured to serve a multi-tenant application.
     *
     * @return {@code true} if the factory would produce multi-tenant storages,
     *         {@code false} otherwise
     */
    boolean isMultitenant();

    /**
     * Retrieves the {@link ColumnTypeRegistry type registry} which declares how to store
     * values of certain types in the {@linkplain Storage storages} generated by this factory.
     *
     * @return immutable registry of type convection strategies
     */
    ColumnTypeRegistry getTypeRegistry();

    /**
     * Creates a new {@link StandStorage} instance.
     */
    StandStorage createStandStorage();

    /**
     * Creates a new {@link AggregateStorage} instance.
     *
     * @param <I>            the type of aggregate IDs
     * @param aggregateClass the class of aggregates to store
     */
    <I> AggregateStorage<I> createAggregateStorage(
            Class<? extends Aggregate<I, ?, ?>> aggregateClass);

    /**
     * Creates a new {@link RecordStorage} instance.
     *
     * @param <I>        the type of entity IDs
     * @param <S>        the type of entity state
     * @param idClass    the class of entity identifiers
     * @param stateClass the class of entity state
     */
    <I, S extends Message> RecordStorage<I> createRecordStorage(Class<I> idClass,
                                                                Class<S> stateClass);

    /**
     * Creates a new {@link ProjectionStorage} instance.
     * @param <I>        the type of stream projection IDs
     * @param <S>        the type of the projection state
     * @param idClass    the class of identifiers
     * @param stateClass the class of the projection state
     */
    <I, S extends Message> ProjectionStorage<I> createProjectionStorage(Class<I> idClass,
                                                                        Class<S> stateClass);

    /**
     * Creates a single-tenant version of the factory.
     *
     * <p>This method is needed for creating single-tenant storages using
     * a multi-tenant instance of a {@code StorageFactory}.
     *
     * @return a single-tenant version of the factory, or {@code this}
     *         if the factory is single-tenant
     */
    StorageFactory toSingleTenant();
}
