# Ensures that the current lib version is not yet published but executing the Gradle
# `checkVersionIncrement` task.

name: Ensure license reports updated

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Configure the checkout of all branches, so that it is possible to run the comparison.
          fetch-depth: 0

      - name: Check that `pom.xml` and `license-report.md` are modified
        shell: bash
        run: chmod +x ./scripts/ensure-required-files-modified-in-PR.sh && ./scripts/ensure-required-files-modified-in-PR.sh
